/**
 * Builds the two artifacts the plugin ships so that authoring a test case
 * needs nothing but `node` and the plugin directory itself.
 *
 *   plugins/enloop/validator/lib.mjs   the parser + linter, bundled, no deps
 *   plugins/enloop/references/grammar.md   the grammar spec, as prose
 *
 * Both are generated from `shared/src` and both are committed, because the
 * plugin is distributed as a directory of files — a user who installs it has
 * no build step and no `node_modules`. Committed build artifacts drift, so
 * `.github/workflows/plugin.yml` rebuilds them on every push and fails if the
 * result differs from what is checked in.
 *
 *   npm run build:plugin
 */
import { build } from "vite";
import { readFile, writeFile, rm } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const validatorDir = path.join(root, "plugins/enloop/validator");
const grammarFile = path.join(root, "plugins/enloop/references/grammar.md");
const source = path.join(root, "shared/src/markdown.ts");

/** The grammar is a doc comment in `markdown.ts` — the spec lives next to the
 * parser it describes, deliberately, so the two cannot disagree. Extracting it
 * rather than maintaining a second copy keeps that true for the plugin's
 * readers too. */
async function buildGrammar() {
  const text = await readFile(source, "utf8");
  const match = /\/\*\*\n \* Grammar\.([\s\S]*?)\n \*\//.exec(text);
  if (!match) throw new Error(`No grammar doc comment found in ${source}`);

  const body = match[0]
    .split("\n")
    .slice(1, -1)
    .map((line) => line.replace(/^ \* ?/, "").replace(/^ \*$/, ""))
    .join("\n")
    .trim();

  const version = /CURRENT_FORMAT_VERSION = "([^"]+)"/.exec(text)?.[1] ?? "unknown";

  await writeFile(
    grammarFile,
    `# The case grammar, format version ${version}

<!-- GENERATED by scripts/build-plugin.mjs from shared/src/markdown.ts.
     Do not edit: the parser and this file are one source, and CI fails when
     they disagree. Change the doc comment in markdown.ts instead. -->

This is the spec the real parser implements, lifted verbatim from the comment
that sits above it. \`@version\` in a case you write is the format version in
this heading. It is reproduced as a code block on purpose: the annotations are
aligned in columns, and reflowing them as prose loses which line each belongs
to.

\`\`\`text
${body}
\`\`\`
`,
    "utf8",
  );
  return version;
}

async function buildBundle() {
  await rm(path.join(validatorDir, "lib.mjs"), { force: true });
  await build({
    configFile: false,
    root,
    logLevel: "warn",
    build: {
      outDir: validatorDir,
      emptyOutDir: false,
      minify: false,
      target: "node20",
      lib: {
        entry: path.join(root, "shared/src/plugin-entry.ts"),
        formats: ["es"],
        fileName: () => "lib.mjs",
      },
      // Nothing is external: the bundle runs where no install has happened.
      rollupOptions: { external: [] },
    },
  });
}

const version = await buildGrammar();
await buildBundle();
console.log(`Built plugin artifacts for grammar ${version}:`);
console.log(`  ${path.relative(root, grammarFile)}`);
console.log(`  ${path.relative(root, path.join(validatorDir, "lib.mjs"))}`);
